---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - release-cert-manager.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - namespace: flux-system
    name: values-cert-manager
    files:
      - values.yaml=values-cert-manager.yaml