---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      interval: 24h0m0s
      sourceRef:
        kind: HelmRepository
        name: helm-repo-jetstack-io
        namespace: flux-system
      version: v1.14.4
  interval: 24h0m0s
  releaseName: cert-manager
  storageNamespace: flux-system
  targetNamespace: cert-manager
  valuesFrom:
    - kind: ConfigMap
      name: values-cert-manager
      valuesKey: values.yaml