apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/weave-gitops
patches:
  - path: delete-release-weave-gitops.yaml
  - path: delete-values-weave-gitops.yaml
  - path: delete-oci-repository-weave-gitops.yaml