apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - oci-repo-weave-gitops.yaml
  - release-weave-gitops.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - namespace: flux-system
    name: values-weave-gitops
    files:
      - values.yaml=values-weave-gitops.yaml