---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: oci-repo-weave-gitops
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: oci://ghcr.io/weaveworks/charts/weave-gitops
  ref:
    tag: '4.0.36'