apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/tf-controller
patches:
  - path: delete-release-cert-manager.yaml
  - path: delete-values-cert-manager.yaml
  - path: delete-namespace-cert-manager.yaml
