---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helm-repo-tofu-controller
  namespace: flux-system
spec:
  interval: 24h
  url: https://flux-iac.github.io/tofu-controller