---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      interval: 24h0m0s
      sourceRef:
        kind: HelmRepository
        name: helm-repo-tofu-controller
        namespace: flux-system
      version: 0.15.1
  interval: 24h0m0s
  releaseName: tf-controller
  storageNamespace: flux-system
  targetNamespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: values-tf-controller
      valuesKey: values.yaml